import { StyleSheet, Platform } from 'react-native';

// Styles function - takes screenWidth, screenHeight, and optional insets (for safe area in modals)
const createStyles = (screenWidth, screenHeight, insets = { top: 0 }) => StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#1a1a1a',
    overflow: 'visible',
  },
  swipeWrapper: {
    flex: 1,
    overflow: 'hidden',
  },
  scrollContainer: {
    flex: 1,
  },
  swipeContainer: {
    flex: 1,
    flexDirection: 'row',
    width: screenWidth * 2, // Two screens side by side
  },
  viewContainer: {
    width: screenWidth,
    flex: 1,
  },
  scrollView: {
    flex: 1,
  },
  // Reserve bottom space inside scroll (like DailyWorkoutScreen) so content is never covered; extra padding for screenIndicator overlay
  scrollContentContainer: {
    flexGrow: 1,
    paddingBottom: 0,
    overflow: 'visible',
  },
  content: {
    paddingHorizontal: Math.max(24, screenWidth * 0.06),
    paddingTop: Math.max(10, screenHeight * 0.012),
    paddingBottom: 0,
    overflow: 'visible',
  },
      exerciseTitleSection: {
        marginBottom: Math.max(10, screenHeight * 0.012),
        paddingTop: 0,
        marginTop: Math.max(-15, screenHeight * -0.02)
      },
      exerciseTitle: {
        fontSize: Math.min(screenWidth * 0.08, 32),
        color: '#ffffff',
        fontWeight: '600',
        textAlign: 'left',
        paddingLeft: Math.max(24, screenWidth * 0.06),
      },
      exerciseTitleCard: {
        backgroundColor: '#2a2a2a',
        borderRadius: Math.max(12, screenWidth * 0.04),
        padding: 0, // Match videoCard padding
        marginBottom: 0, // Match videoCard margin
        marginTop: 0, // Match videoCard margin (removed negative margin)
        borderWidth: 1,
        borderColor: 'rgba(255, 255, 255, 0.2)',
        shadowColor: 'rgba(255, 255, 255, 0.4)',
        shadowOffset: { width: 0, height: 0 },
        shadowOpacity: 1,
        shadowRadius: 2,
        elevation: 2,
        height: Math.max(400, screenHeight * 0.525), // 400px min, 50% of screen
        width: screenWidth - Math.max(48, screenWidth * 0.12), // Match videoCard width
        overflow: 'visible',
        position: 'relative', // Match videoCard position
        flexDirection: 'column',
        justifyContent: 'flex-start',
      },
      exerciseTitleCardContent: {
        paddingTop: Math.max(20, screenWidth * 0.05),
        paddingHorizontal: Math.max(20, screenWidth * 0.05),
        paddingBottom: Math.max(10, screenWidth * 0.025),
        width: '100%',
        height: '100%',
      },
      exerciseTitleCardNoPadding: {
        backgroundColor: '#44454B',
        borderRadius: 12,
        padding: 0,
        marginBottom: 0,
        marginTop: 10,
        borderWidth: 0,
        borderColor: 'transparent',
        height: 220, // Slightly taller card
        width: screenWidth - 48, // Full width minus padding
        overflow: 'hidden',
      },
      video: {
        flex: 1,
        width: '100%',
        height: '100%',
      },
      videoContainer: {
        flex: 1,
        width: '100%',
        height: '100%',
      },
      videoErrorText: {
        fontSize: 16,
        color: '#ffffff',
        textAlign: 'center',
        marginTop: 100,
      },
      videoLoadingContainer: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        backgroundColor: '#333333',
      },
      videoLoadingText: {
        fontSize: 14,
        color: '#ffffff',
        marginTop: 10,
        opacity: 0.8,
      },
      videoPlaceholder: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        backgroundColor: '#333333',
      },
      videoPlaceholderText: {
        fontSize: 16,
        color: '#ffffff',
        opacity: 0.6,
      },
      instructionsTitle: {
        fontSize: Math.min(screenWidth * 0.05, 20),
        fontWeight: '600',
        color: '#ffffff',
        marginBottom: Math.max(12, screenHeight * 0.015),
      },
      objetivosSection: {
        marginTop: Math.max(-20, screenHeight * -0.025),
        marginBottom: Math.max(15, screenHeight * 0.02),
        paddingLeft: Math.max(24, screenWidth * 0.06),
      },
      objetivosTitle: {
        fontSize: Math.min(screenWidth * 0.05, 20),
        fontWeight: '600',
        color: '#ffffff',
        marginLeft: 0,
      },
      exerciseDescriptionText: {
        fontSize: Math.min(screenWidth * 0.035, 14),
        color: '#ffffff',
        lineHeight: Math.max(22, screenHeight * 0.03),
        textAlign: 'left',
        fontWeight: '500',
      },
      descriptionScrollView: {
        flex: 1,
        paddingBottom: 20, // Add padding to prevent text from being covered
      },
      topGradient: {
    position: 'absolute',
        top: 40,
    left: 0,
    right: 0,
        height: 25,
        backgroundColor: 'rgba(42, 42, 42, 0.9)',
        borderTopLeftRadius: 12,
        borderTopRightRadius: 12,
        zIndex: 1,
      },
      scrollIndicator: {
        position: 'absolute',
        bottom: 0,
        left: 0,
        right: 0,
        height: 35,
        backgroundColor: 'rgba(42, 42, 42, 0.9)',
        borderBottomLeftRadius: 12,
        borderBottomRightRadius: 12,
    alignItems: 'center',
        justifyContent: 'center',
        paddingTop: 8,
        paddingBottom: 8,
      },
      scrollIndicatorText: {
        fontSize: 11,
        fontWeight: '500',
        color: '#ffffff',
        textAlign: 'center',
      },
      topCardsContainer: {
        marginBottom: Math.max(5, screenHeight * 0.006),
        overflow: 'visible',
        // Break out of content padding so ScrollView is full width; lateral peek like DailyWorkoutScreen
        marginHorizontal: -Math.max(24, screenWidth * 0.06),
      },
      topCardsContent: {
        gap: 15,
        overflow: 'visible',
        paddingHorizontal: Math.max(24, screenWidth * 0.06),
      },
      topCardsIndicator: {
    alignItems: 'center',
        marginBottom: Math.max(15, screenHeight * 0.018),
      },
      horizontalCardsScrollView: {
        marginBottom: Math.max(15, screenHeight * 0.018),
        overflow: 'visible',
        // Break out of content padding so objectives cards spill laterally (like top cards)
        marginHorizontal: -Math.max(24, screenWidth * 0.06),
      },
      horizontalCardsContainer: {
        flexDirection: 'row',
        gap: Math.max(10, screenWidth * 0.025),
        overflow: 'visible',
        paddingHorizontal: Math.max(24, screenWidth * 0.06),
      },
      horizontalCard: {
        minWidth: Math.max(140, screenWidth * 0.35),
        maxWidth: Math.max(160, screenWidth * 0.4),
        backgroundColor: '#2a2a2a',
        borderRadius: Math.max(12, screenWidth * 0.04),
    borderWidth: 1,
        borderColor: 'rgba(255, 255, 255, 0.2)',
        shadowColor: 'rgba(255, 255, 255, 0.4)',
        shadowOffset: { width: 0, height: 0 },
        shadowOpacity: 1,
        shadowRadius: 2,
        elevation: 2,
        height: Math.max(80, screenHeight * 0.1),
        justifyContent: 'center',
        alignItems: 'center',
        padding: Math.max(15, screenWidth * 0.04),
        paddingRight: Math.max(25, screenWidth * 0.06), // Extra padding for info icon
        overflow: 'visible',
      },
      metricTitle: {
        fontSize: Math.min(screenWidth * 0.03, 12),
        fontWeight: '500',
        color: '#ffffff',
        opacity: 0.8,
        textAlign: 'center',
        marginBottom: Math.max(4, screenHeight * 0.005),
      },
      metricValue: {
        fontSize: Math.min(screenWidth * 0.06, 24),
        fontWeight: '600',
        color: '#ffffff',
        textAlign: 'center',
      },
      metricValueContainer: {
        alignItems: 'center',
        justifyContent: 'center',
        marginBottom: Math.max(4, screenHeight * 0.005),
      },
      exerciseInfoText: {
        fontSize: 16,
        color: '#ffffff',
        textAlign: 'center',
      },
  screenIndicator: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    alignItems: 'center',
    backgroundColor: '#1a1a1a',
    paddingTop: Math.max(10, screenHeight * 0.012),
    paddingBottom: Math.max(15, screenHeight * 0.018),
  },
  loadingContainer: {
    flex: 1,
    justifyContent: 'flex-start',
    alignItems: 'center',
    paddingTop: Math.max(120, screenHeight * 0.15), // Add space to account for header
  },
  simpleLoadingContainer: {
    position: 'absolute',
    top: Math.max(300, screenHeight * 0.4), // Fixed position from top
    left: 0,
    right: 0,
    alignItems: 'center',
    justifyContent: 'center',
  },
  loadingText: {
    color: '#cccccc',
    fontSize: Math.min(screenWidth * 0.04, 16),
    fontWeight: '400',
    marginTop: Math.max(12, screenHeight * 0.015),
  },
  errorContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: Math.max(24, screenWidth * 0.06),
  },
  errorText: {
    color: '#ff4444',
    fontSize: Math.min(screenWidth * 0.045, 18),
    fontWeight: '600',
    textAlign: 'center',
    marginBottom: Math.max(10, screenHeight * 0.012),
  },
  errorSubtext: {
    color: '#cccccc',
    fontSize: Math.min(screenWidth * 0.035, 14),
    fontWeight: '400',
    textAlign: 'center',
    marginBottom: Math.max(20, screenHeight * 0.025),
  },
  backButton: {
    backgroundColor: '#007AFF',
    paddingHorizontal: Math.max(20, screenWidth * 0.05),
    paddingVertical: Math.max(12, screenHeight * 0.015),
    borderRadius: Math.max(8, screenWidth * 0.02),
  },
  backButtonText: {
    color: '#ffffff',
    fontSize: Math.min(screenWidth * 0.04, 16),
    fontWeight: '600',
  },
  exerciseInfoCard: {
    backgroundColor: '#2a2a2a',
    borderRadius: Math.max(12, screenWidth * 0.04),
    padding: Math.max(20, screenWidth * 0.05),
    marginBottom: Math.max(20, screenHeight * 0.025),
    borderWidth: 1,
    borderColor: '#3a3a3a',
  },
  exerciseName: {
    fontSize: Math.min(screenWidth * 0.06, 24),
    fontWeight: '700',
    color: '#ffffff',
    textAlign: 'center',
    marginBottom: Math.max(16, screenHeight * 0.02),
  },
  exerciseDescription: {
    fontSize: Math.min(screenWidth * 0.04, 16),
    fontWeight: '400',
    color: '#cccccc',
    lineHeight: Math.max(22, screenHeight * 0.03),
    marginBottom: Math.max(16, screenHeight * 0.02),
    textAlign: 'center',
  },
  infoRow: {
    flexDirection: 'row',
    marginBottom: Math.max(8, screenHeight * 0.01),
  },
  infoLabel: {
    fontSize: Math.min(screenWidth * 0.035, 14),
    fontWeight: '600',
    color: '#888888',
    width: Math.max(80, screenWidth * 0.2),
  },
  infoValue: {
    fontSize: Math.min(screenWidth * 0.035, 14),
    fontWeight: '400',
    color: '#ffffff',
    flex: 1,
  },
  setInfoCard: {
    backgroundColor: '#2a2a2a',
    borderRadius: Math.max(12, screenWidth * 0.04),
    padding: Math.max(20, screenWidth * 0.05),
    marginBottom: Math.max(24, screenHeight * 0.03),
    borderWidth: 1,
    borderColor: '#3a3a3a',
  },
  setTitle: {
    fontSize: Math.min(screenWidth * 0.05, 20),
    fontWeight: '700',
    color: '#007AFF',
    textAlign: 'center',
    marginBottom: Math.max(20, screenHeight * 0.025),
  },
  setDetailRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: Math.max(8, screenHeight * 0.01),
    borderBottomWidth: 1,
    borderBottomColor: '#3a3a3a',
  },
  setDetailLabel: {
    fontSize: Math.min(screenWidth * 0.04, 16),
    fontWeight: '500',
    color: '#cccccc',
  },
  setDetailValue: {
    fontSize: Math.min(screenWidth * 0.045, 18),
    color: '#ffffff',
    fontWeight: '600',
  },
  navigationContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: Math.max(12, screenWidth * 0.03),
  },
  navButton: {
    flex: 1,
    paddingVertical: Math.max(16, screenHeight * 0.02),
    borderRadius: Math.max(12, screenWidth * 0.04),
    alignItems: 'center',
  },
  previousButton: {
    backgroundColor: 'transparent',
    borderWidth: 2,
    borderColor: '#666666',
  },
  nextButton: {
    backgroundColor: '#007AFF',
  },
  disabledButton: {
    opacity: 0.5,
  },
  navButtonText: {
    fontSize: Math.min(screenWidth * 0.04, 16),
    fontWeight: '600',
    color: '#ffffff',
  },
  // Exercise List View Styles
  exerciseListView: {
    flex: 1,
  },
  exerciseListContent: {
    paddingHorizontal: Math.max(24, screenWidth * 0.06),
    paddingTop: Math.max(10, screenHeight * 0.012), // Match main content padding
    paddingBottom: 24,
  },
  exerciseListTitleSection: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: Math.max(10, screenHeight * 0.012),
    paddingTop: 0,
    marginTop: 0,
    // paddingHorizontal removed - handled by contentContainerStyle in FlatList
  },
  exerciseListTitle: {
    fontSize: Math.min(screenWidth * 0.08, 32),
    color: '#ffffff',
    fontWeight: '600',
    textAlign: 'left',
    flex: 1,
  },
  editButtonSection: {
    paddingHorizontal: Math.max(24, screenWidth * 0.06),
    marginBottom: Math.max(15, screenHeight * 0.018),
    alignItems: 'center',
  },
  editButton: {
    backgroundColor: 'rgba(255, 255, 255, 0.05)',
    paddingHorizontal: 16,
    paddingVertical: 8,
    borderRadius: Math.max(12, screenWidth * 0.04),
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.1)',
    shadowColor: 'rgba(255, 255, 255, 0.4)',
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 1,
    shadowRadius: 2,
    elevation: 2,
    alignItems: 'center',
  },
  editButtonText: {
    color: '#ffffff',
    fontSize: 14,
    fontWeight: '600',
  },
  editButtonActive: {
    backgroundColor: '#ff6b6b',
  },

  // Edit Mode Controls Styles
  editModeControls: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },

  // Edit Mode Exercise Card Styles
  editModeExerciseList: {
    // No padding - cards are in the same container as normal exercises
  },
  editModeExerciseCard: {
    backgroundColor: '#2a2a2a',
    borderRadius: Math.max(12, screenWidth * 0.04),
    marginBottom: Math.max(16, screenHeight * 0.02),
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.2)',
    shadowColor: 'rgba(255, 255, 255, 0.4)',
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 1,
    shadowRadius: 2,
    elevation: 2,
    overflow: 'visible',
  },
  editModeExerciseCardContent: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: Math.max(20, screenWidth * 0.05),
    minHeight: Math.max(60, screenHeight * 0.075),
  },
  editModeExerciseCardActive: {
    opacity: 0.8,
    transform: [{ scale: 1.02 }],
  },
  dropLine: {
    height: 3,
    backgroundColor: '#ffffff',
    marginVertical: Math.max(4, screenHeight * 0.005),
    borderRadius: 2,
    shadowColor: '#ffffff',
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.8,
    shadowRadius: 4,
    elevation: 4,
  },
  dragHandle: {
    marginRight: Math.max(16, screenWidth * 0.04),
    alignSelf: 'center',
    justifyContent: 'center',
    alignItems: 'center',
  },
  editModeExerciseContent: {
    flex: 1,
    marginRight: 15,
  },
  editModeExerciseName: {
    fontSize: Math.min(screenWidth * 0.04, 16),
    fontWeight: '600',
    color: '#ffffff',
  },
  removeExerciseButton: {
    backgroundColor: 'rgba(255, 255, 255, 0.05)',
    paddingHorizontal: 16,
    paddingVertical: 8,
    borderRadius: Math.max(12, screenWidth * 0.04),
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.1)',
    shadowColor: 'rgba(255, 255, 255, 0.4)',
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 1,
    shadowRadius: 2,
    elevation: 2,
    justifyContent: 'center',
    alignItems: 'center',
  },
  removeExerciseButtonText: {
    color: '#ffffff',
    fontSize: 14,
    fontWeight: '600',
  },

  // Edit Modal Styles
  editModalContainer: {
    flex: 1,
    backgroundColor: '#1A1A1A',
  },
  editModalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: 20,
    borderBottomWidth: 1,
    borderBottomColor: '#333',
  },
  editModalTitle: {
    fontSize: 24,
    fontWeight: '600',
    color: '#ffffff',
  },
  editModalActions: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 15,
  },
  editModalContent: {
    flex: 1,
    padding: 20,
  },
  editExerciseItem: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#2a2a2a',
    marginVertical: 5,
    padding: 15,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#333',
  },
  dragHandleText: {
    color: '#666',
    fontSize: 16,
  },
  editExerciseContent: {
    flex: 1,
  },
  editExerciseName: {
    fontSize: 16,
    fontWeight: '600',
    color: '#ffffff',
  },
  editExerciseInfo: {
    fontSize: 14,
    color: '#999',
    marginTop: 2,
  },
  exerciseActions: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
  },
  moveButton: {
    backgroundColor: '#444',
    padding: 8,
    borderRadius: 6,
  },
  moveButtonText: {
    color: '#ffffff',
    fontSize: 16,
    fontWeight: '600',
  },
  saveButton: {
    backgroundColor: 'rgba(255, 255, 255, 0.05)',
    paddingHorizontal: 15,
    paddingVertical: 8,
    borderRadius: Math.max(12, screenWidth * 0.04),
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.1)',
    shadowColor: 'rgba(255, 255, 255, 0.4)',
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 1,
    shadowRadius: 2,
    elevation: 2,
  },
  saveButtonText: {
    color: '#ffffff',
    fontSize: 14,
    fontWeight: '600',
  },
  closeButton: {
    padding: Math.max(8, screenWidth * 0.02),
    justifyContent: 'center',
    alignItems: 'center',
  },
  closeButtonText: {
    fontSize: Math.min(screenWidth * 0.05, 20),
    color: '#ffffff',
    fontWeight: '600',
  },

  // Add Exercise Modal Styles
  addExerciseModalContainer: {
    flex: 1,
    backgroundColor: '#1A1A1A',
    paddingTop: Platform.OS === 'web' ? 50 : Math.max(50, (insets.top || 0) + 50),
  },
  addExerciseModalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: 20,
    paddingLeft: Math.max(30, screenWidth * 0.12),
    paddingTop: 20,
  },
  addExerciseModalHeaderActions: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  addExerciseModalTitle: {
    fontSize: 24,
    fontWeight: '600',
    color: '#ffffff',
  },
  searchContainer: {
    marginBottom: 15,
  },
  searchInputContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#2a2a2a',
    borderRadius: Math.max(12, screenWidth * 0.04),
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.2)',
    shadowColor: 'rgba(255, 255, 255, 0.4)',
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 1,
    shadowRadius: 2,
    elevation: 2,
    paddingHorizontal: Math.max(16, screenWidth * 0.04),
    paddingVertical: Math.max(12, screenHeight * 0.015),
    marginHorizontal: Math.max(20, screenWidth * 0.05),
  },
  searchIcon: {
    marginRight: 12,
  },
  searchInput: {
    flex: 1,
    fontSize: 14,
    color: '#ffffff',
    opacity: 0.8,
  },
  addExerciseModalContent: {
    flex: 1,
    padding: 20,
  },
  addExerciseCard: {
    backgroundColor: '#2a2a2a',
    borderRadius: Math.max(12, screenWidth * 0.04),
    marginBottom: Math.max(16, screenHeight * 0.02),
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.2)',
    shadowColor: 'rgba(255, 255, 255, 0.4)',
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 1,
    shadowRadius: 2,
    elevation: 2,
    overflow: 'visible',
  },
  addExerciseCardContent: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: Math.max(20, screenWidth * 0.05),
    minHeight: Math.max(60, screenHeight * 0.075),
  },
  addExerciseContent: {
    flex: 1,
    marginRight: 15,
  },
  addExerciseName: {
    fontSize: Math.min(screenWidth * 0.04, 16),
    fontWeight: '600',
    color: '#ffffff',
  },
  addExerciseButton: {
    backgroundColor: 'rgba(255, 255, 255, 0.05)',
    paddingHorizontal: 16,
    paddingVertical: 8,
    borderRadius: Math.max(12, screenWidth * 0.04),
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.1)',
    shadowColor: 'rgba(255, 255, 255, 0.4)',
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 1,
    shadowRadius: 2,
    elevation: 2,
    justifyContent: 'center',
    alignItems: 'center',
    minWidth: 40,
    minHeight: 32,
  },
  addExerciseButtonText: {
    color: '#ffffff',
    fontSize: 14,
    fontWeight: '600',
  },
  addExerciseExpandedCard: {
    backgroundColor: '#3a3a3a',
    borderRadius: Math.max(12, screenWidth * 0.04),
    padding: Math.max(12, screenWidth * 0.03),
    flexDirection: 'column',
    marginBottom: Math.max(12, screenHeight * 0.015),
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.2)',
    shadowColor: 'rgba(255, 255, 255, 0.4)',
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 1,
    shadowRadius: 2,
    elevation: 2,
  },
  addExerciseExpandedCardBorder: {
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.2)',
    shadowColor: 'rgba(255, 255, 255, 0.4)',
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 1,
    shadowRadius: 2,
    elevation: 2,
  },
  addExerciseCardBorder: {
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.2)',
    shadowColor: 'rgba(255, 255, 255, 0.4)',
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 1,
    shadowRadius: 2,
    elevation: 2,
  },
  addExerciseVideoContainer: {
    width: '85%',
    height: 430, // Same height as swap modal
    borderRadius: Math.max(12, screenWidth * 0.04),
    marginBottom: Math.max(12, screenHeight * 0.015),
    overflow: 'hidden',
    alignSelf: 'center',
  },
  addExerciseVideoWrapper: {
    width: '100%',
    height: '100%',
    position: 'relative',
  },
  addExerciseVideo: {
    width: '100%',
    height: '100%',
  },
  addExerciseVideoDimmingLayer: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: 'rgba(0, 0, 0, 0.3)',
    zIndex: 1,
  },
  addExerciseVideoPauseOverlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: 2,
  },
  addExerciseVideoVolumeOverlay: {
    position: 'absolute',
    top: Math.max(12, screenHeight * 0.015),
    right: Math.max(12, screenWidth * 0.03),
    width: Math.max(40, screenWidth * 0.1),
    height: Math.max(40, screenWidth * 0.1),
    borderRadius: Math.max(20, screenWidth * 0.05),
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: 3,
  },
  addExerciseVideoPlaceholder: {
    width: '100%',
    height: '100%',
    backgroundColor: '#666666',
    justifyContent: 'center',
    alignItems: 'center',
  },
  addExerciseVideoPlaceholderText: {
    color: '#ffffff',
    fontSize: Math.min(screenWidth * 0.025, 10),
    fontWeight: '500',
    textAlign: 'center',
  },
  addExerciseVideoPreviewPlaceholder: {
    width: '85%',
    height: 430,
    borderRadius: Math.max(12, screenWidth * 0.04),
    marginBottom: Math.max(12, screenHeight * 0.015),
    overflow: 'hidden',
    alignSelf: 'center',
    backgroundColor: 'rgba(255, 255, 255, 0.06)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  addExerciseVideoPreviewPlaceholderText: {
    color: 'rgba(255, 255, 255, 0.6)',
    fontSize: Math.min(screenWidth * 0.035, 14),
    fontWeight: '500',
    textAlign: 'center',
  },
  addExerciseExpandedName: {
    color: '#ffffff',
    fontSize: Math.min(screenWidth * 0.04, 16),
    fontWeight: '600',
  },
  exerciseOption: {
    backgroundColor: '#2a2a2a',
    marginVertical: 5,
    padding: 15,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#333',
  },
  exerciseOptionName: {
    fontSize: 16,
    fontWeight: '600',
    color: '#ffffff',
  },
  // Filter Button Styles
  filterButton: {
    backgroundColor: 'rgba(255, 255, 255, 0.05)',
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: Math.max(8, screenWidth * 0.02),
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.1)',
  },
  filterButtonActive: {
    backgroundColor: 'rgba(191, 168, 77, 0.2)',
    borderColor: '#BFA84D',
  },
  filterButtonText: {
    color: '#ffffff',
    fontSize: 14,
    fontWeight: '600',
  },
  filterButtonTextActive: {
    color: '#BFA84D',
  },
  filterButtonBadge: {
    color: '#BFA84D',
  },
  activeFiltersContainer: {
    paddingHorizontal: Math.max(20, screenWidth * 0.05),
    paddingVertical: 10,
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(255, 255, 255, 0.1)',
  },
  activeFiltersScroll: {
    flexDirection: 'row',
  },
  activeFilterChip: {
    backgroundColor: 'rgba(191, 168, 77, 0.2)',
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: Math.max(8, screenWidth * 0.02),
    marginRight: 8,
    borderWidth: 1,
    borderColor: '#BFA84D',
  },
  activeFilterChipText: {
    color: '#BFA84D',
    fontSize: 12,
    fontWeight: '500',
  },
  clearAllFiltersButton: {
    backgroundColor: 'transparent',
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: Math.max(8, screenWidth * 0.02),
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.3)',
  },
  clearAllFiltersButtonText: {
    color: '#ffffff',
    fontSize: 12,
    fontWeight: '500',
  },
  // Filter Modal Styles
  filterModalContainer: {
    flex: 1,
    backgroundColor: '#1A1A1A',
    paddingTop: Platform.OS === 'web' ? 50 : Math.max(50, (insets.top || 0) + 50),
  },
  filterModalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: 20,
    paddingLeft: Math.max(30, screenWidth * 0.12),
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(255, 255, 255, 0.1)',
  },
  filterModalTitle: {
    fontSize: 24,
    fontWeight: '600',
    color: '#ffffff',
  },
  filterModalContent: {
    flex: 1,
    padding: 20,
  },
  filterSection: {
    marginBottom: 30,
  },
  filterSectionTitle: {
    fontSize: 18,
    fontWeight: '600',
    color: '#ffffff',
    marginBottom: 15,
  },
  muscleSilhouetteContainer: {
    backgroundColor: '#2a2a2a',
    borderRadius: Math.max(12, screenWidth * 0.04),
    padding: 15,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 15,
  },
  selectedItemsContainer: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
  },
  filterChip: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(191, 168, 77, 0.2)',
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: Math.max(8, screenWidth * 0.02),
    borderWidth: 1,
    borderColor: '#BFA84D',
    gap: 8,
  },
  filterChipText: {
    color: '#BFA84D',
    fontSize: 14,
    fontWeight: '500',
  },
  filterChipRemove: {
    color: '#BFA84D',
    fontSize: 18,
    fontWeight: 'bold',
  },
  implementsContainer: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
  },
  implementChip: {
    backgroundColor: 'rgba(255, 255, 255, 0.05)',
    paddingHorizontal: 16,
    paddingVertical: 10,
    borderRadius: Math.max(8, screenWidth * 0.02),
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.1)',
  },
  implementChipSelected: {
    backgroundColor: 'rgba(191, 168, 77, 0.2)',
    borderColor: '#BFA84D',
  },
  implementChipText: {
    color: '#ffffff',
    fontSize: 14,
    fontWeight: '500',
  },
  implementChipTextSelected: {
    color: '#BFA84D',
  },
  filterModalActions: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: 20,
    borderTopWidth: 1,
    borderTopColor: 'rgba(255, 255, 255, 0.1)',
    gap: 12,
  },
  filterClearButton: {
    flex: 1,
    backgroundColor: 'rgba(255, 255, 255, 0.05)',
    paddingVertical: 14,
    borderRadius: Math.max(12, screenWidth * 0.04),
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.1)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  filterClearButtonText: {
    color: '#ffffff',
    fontSize: 16,
    fontWeight: '600',
  },
  filterApplyButton: {
    flex: 1,
    backgroundColor: 'rgba(191, 168, 77, 0.2)',
    paddingVertical: 14,
    borderRadius: Math.max(12, screenWidth * 0.04),
    borderWidth: 1,
    borderColor: '#BFA84D',
    alignItems: 'center',
    justifyContent: 'center',
  },
  filterApplyButtonText: {
    color: '#BFA84D',
    fontSize: 16,
    fontWeight: '600',
  },
  filterButtonDisabled: {
    opacity: 0.5,
  },
  filterButtonTextDisabled: {
    opacity: 0.5,
  },
  exerciseOptionDescription: {
    fontSize: 14,
    color: '#999',
    marginTop: 5,
  },
  emptyStateContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    paddingVertical: 50,
  },
  emptyStateText: {
    fontSize: 18,
    fontWeight: '600',
    color: '#ffffff',
    textAlign: 'center',
    marginBottom: 10,
  },
  emptyStateSubtext: {
    fontSize: 14,
    color: '#999',
    textAlign: 'center',
    paddingHorizontal: 20,
  },

  exerciseListItem: {
    backgroundColor: '#2a2a2a',
    borderRadius: Math.max(12, screenWidth * 0.04),
    marginBottom: Math.max(16, screenHeight * 0.02),
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.2)',
    shadowColor: 'rgba(255, 255, 255, 0.4)',
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 1,
    shadowRadius: 2,
    elevation: 2,
    overflow: 'visible',
  },
  exerciseCard: {
    flexDirection: 'row',
    paddingHorizontal: Math.max(20, screenWidth * 0.05),
    alignItems: 'center',
    minHeight: Math.max(60, screenHeight * 0.075),
  },
  exerciseNumber: {
    fontSize: Math.min(screenWidth * 0.08, 32),
    fontWeight: '700',
    color: '#ffffff',
    marginRight: Math.max(16, screenWidth * 0.04),
    alignSelf: 'center',
  },
  exerciseContent: {
    flex: 1,
  },
  exerciseItemTitle: {
    fontSize: Math.min(screenWidth * 0.04, 16),
    fontWeight: '600',
    color: '#ffffff',
  },
  exerciseInfo: {
    fontSize: Math.min(screenWidth * 0.03, 12),
    fontWeight: '400',
    color: '#ffffff',
    opacity: 0.8,
  },
  exerciseItemArrow: {
    // Styles for the SVG icon
  },
  arrowButton: {
    padding: 8,
    justifyContent: 'center',
    alignItems: 'center',
  },
  arrowRight: {
    transform: [{ rotate: '180deg' }], // ChevronLeft rotated 180deg = pointing right
  },
  arrowDown: {
    transform: [{ rotate: '270deg' }], // ChevronLeft rotated 270deg = pointing down
  },
  setsContainer: {
    paddingTop: 0,
    paddingBottom: Math.max(16, screenHeight * 0.02),
  },
  setTrackingRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: Math.max(16, screenWidth * 0.04),
    paddingVertical: Math.max(4, screenHeight * 0.005),
    position: 'relative',
  },
  currentSetOverlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: 'rgba(255, 255, 255, 0.2)',
    borderRadius: 8,
    zIndex: 1,
    pointerEvents: 'none',
  },
  setNumberSpace: {
    width: Math.max(20, screenWidth * 0.05),
    marginRight: Math.max(20, screenWidth * 0.05),
    marginLeft: Math.max(26, screenWidth * 0.065),
  },
  setNumber: {
    fontSize: Math.min(screenWidth * 0.045, 18),
    fontWeight: '600',
    color: '#ffffff',
    marginRight: Math.max(20, screenWidth * 0.05),
    minWidth: Math.max(20, screenWidth * 0.05),
    textAlign: 'left',
  },
  setNumberContainer: {
    justifyContent: 'center',
    alignItems: 'center',
    paddingVertical: Math.max(8, screenHeight * 0.01),
    paddingHorizontal: Math.max(4, screenWidth * 0.01),
    marginLeft: Math.max(26, screenWidth * 0.065),
  },
  setInputsContainer: {
    flexDirection: 'row',
    flex: 1,
    paddingRight: Math.max(20, screenWidth * 0.05),
  },
  inputGroup: {
    // No padding - boxes should touch each other
  },
  headerLabel: {
    fontSize: Math.min(screenWidth * 0.035, 14),
    fontWeight: '600',
    color: '#ffffff',
    textAlign: 'center',
  },
  setInput: {
    backgroundColor: '#3a3a3a',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.2)',
    shadowColor: 'rgba(255, 255, 255, 0.4)',
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 1,
    shadowRadius: 2,
    elevation: 2,
    borderRadius: Math.max(8, screenWidth * 0.02),
    paddingHorizontal: Math.max(8, screenWidth * 0.02),
    paddingVertical: Math.max(6, screenHeight * 0.007),
    color: '#ffffff',
    fontSize: Math.min(screenWidth * 0.04, 16),
    fontWeight: '400',
    textAlign: 'center',
    flex: 1,
  },
  setInputError: {
    borderColor: '#ff4444',
    borderWidth: 2,
    backgroundColor: 'rgba(255, 68, 68, 0.1)',
  },
  previousValue: {
    fontSize: Math.min(screenWidth * 0.04, 16),
    fontWeight: '400',
    color: '#ffffff',
    textAlign: 'left',
    flex: 1,
    paddingVertical: Math.max(6, screenHeight * 0.007),
    paddingHorizontal: Math.max(8, screenWidth * 0.02),
    textAlignVertical: 'center',
  },
  // Left Menu Button Styles (moved to WakeHeader component)
  // Removed - menu button is now integrated in WakeHeader
  // Modal Styles
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    justifyContent: 'flex-start',
    alignItems: 'flex-start',
    paddingTop: Math.max(100, screenHeight * 0.12), // Position below header
    paddingLeft: Math.max(24, screenWidth * 0.06),
  },
  menuModal: {
    backgroundColor: '#2a2a2a',
    borderRadius: Math.max(12, screenWidth * 0.04),
    paddingVertical: Math.max(8, screenHeight * 0.01),
    minWidth: Math.max(300, screenWidth * 0.5),
    width: 'auto',
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 4,
    },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 8,
  },
  menuOption: {
    paddingVertical: Math.max(16, screenHeight * 0.02),
    paddingHorizontal: Math.max(20, screenWidth * 0.05),
    borderBottomWidth: 1,
    borderBottomColor: '#3a3a3a',
  },
  menuOptionLast: {
    paddingVertical: Math.max(16, screenHeight * 0.02),
    paddingHorizontal: Math.max(20, screenWidth * 0.05),
    // No border for the last item
  },
  menuOptionContent: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: Math.max(12, screenWidth * 0.03),
  },
  menuOptionText: {
    color: '#ffffff',
    fontSize: Math.min(screenWidth * 0.037, 15),
    fontWeight: '500',
    flex: 1,
  },
  // Set Input Button Styles
  inputSetButton: {
    backgroundColor: 'rgba(191, 168, 77, 0.2)',
    borderRadius: Math.max(12, screenWidth * 0.04),
    paddingVertical: Math.max(16, screenHeight * 0.02),
    paddingHorizontal: Math.max(20, screenWidth * 0.05),
    marginBottom: Math.max(16, screenHeight * 0.02),
    alignItems: 'center',
    borderWidth: 0.2,
    borderColor: '#ffffff',
    // Shadow removed - was causing offset bottom shadow
    shadowOpacity: 0,
    elevation: 0,
  },
  inputSetButtonText: {
    color: 'rgba(191, 168, 77, 1)',
    fontSize: Math.min(screenWidth * 0.04, 16),
    fontWeight: '600',
  },
  // Set Input Modal Styles
  setInputModalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    justifyContent: 'flex-end',
  },
  setInputModal: {
    backgroundColor: '#2a2a2a',
    borderTopLeftRadius: Math.max(20, screenWidth * 0.05),
    borderTopRightRadius: Math.max(20, screenWidth * 0.05),
    maxHeight: '90%',
    minHeight: '80%',
  },
  setInputModalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: Math.max(20, screenWidth * 0.05),
    paddingVertical: Math.max(16, screenHeight * 0.02),
  },
  setInputModalTitle: {
    fontSize: Math.min(screenWidth * 0.045, 18),
    fontWeight: '600',
    color: '#ffffff',
    flex: 1,
  },
  setInputModalContent: {
    flex: 1,
    paddingHorizontal: Math.max(20, screenWidth * 0.05),
    paddingVertical: Math.max(16, screenHeight * 0.02),
  },
  setInputField: {
    marginBottom: Math.max(20, screenHeight * 0.025),
  },
  setInputFieldLabel: {
    fontSize: Math.min(screenWidth * 0.04, 16),
    fontWeight: '500',
    color: '#ffffff',
    marginBottom: Math.max(8, screenHeight * 0.01),
  },
  setInputFieldInput: {
    backgroundColor: '#3a3a3a',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.2)',
    shadowColor: 'rgba(255, 255, 255, 0.4)',
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 1,
    shadowRadius: 2,
    elevation: 2,
    borderRadius: Math.max(8, screenWidth * 0.02),
    paddingHorizontal: Math.max(16, screenWidth * 0.04),
    paddingVertical: Math.max(12, screenHeight * 0.015),
    color: '#ffffff',
    fontSize: Math.min(screenWidth * 0.04, 16),
    fontWeight: '400',
  },
  setInputFieldInputError: {
    borderColor: '#ff4444',
    borderWidth: 2,
    backgroundColor: 'rgba(255, 68, 68, 0.1)',
  },
  setInputModalFooter: {
    flexDirection: 'row',
    paddingHorizontal: Math.max(20, screenWidth * 0.05),
    paddingVertical: Math.max(16, screenHeight * 0.02),
    paddingBottom: 24,
    justifyContent: 'center',
  },
  cancelSetButton: {
    flex: 1,
    backgroundColor: 'transparent',
    borderWidth: 1,
    borderColor: '#666666',
    borderRadius: Math.max(8, screenWidth * 0.02),
    paddingVertical: Math.max(12, screenHeight * 0.015),
    alignItems: 'center',
  },
  cancelSetButtonText: {
    color: '#cccccc',
    fontSize: Math.min(screenWidth * 0.04, 16),
    fontWeight: '600',
  },
  saveSetButton: {
    backgroundColor: 'rgba(191, 168, 77, 0.2)',
    borderRadius: Math.max(12, screenWidth * 0.04),
    paddingVertical: Math.max(18, screenHeight * 0.022),
    paddingHorizontal: Math.max(40, screenWidth * 0.1),
    alignItems: 'center',
    borderColor: '#ffffff',
    minWidth: Math.max(200, screenWidth * 0.5),
    // Shadow removed - was causing offset bottom shadow
    shadowOpacity: 0,
    elevation: 0,
  },
  saveSetButtonText: {
    color: 'rgba(191, 168, 77, 1)',
    fontSize: Math.min(screenWidth * 0.04, 16),
    fontWeight: '600',
  },
  saveSetButtonDisabled: {
    backgroundColor: '#666666',
    opacity: 0.6,
    shadowOpacity: 0,
  },
  saveSetButtonTextDisabled: {
    color: '#cccccc',
  },
  // Timer button — gold when available (matches inputSetButton)
  timerButton: {
    width: Math.max(60, screenWidth * 0.15),
    backgroundColor: 'rgba(191, 168, 77, 0.2)',
    borderRadius: Math.max(12, screenWidth * 0.04),
    paddingVertical: Math.max(14, screenHeight * 0.017),
    alignItems: 'center',
    justifyContent: 'center',
    shadowOpacity: 0,
    elevation: 0,
  },
  // Timer Modal — big lock-screen style time, gold accents
  timerModalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    justifyContent: 'flex-end',
  },
  timerModal: {
    backgroundColor: '#2a2a2a',
    borderTopLeftRadius: Math.max(20, screenWidth * 0.05),
    borderTopRightRadius: Math.max(20, screenWidth * 0.05),
    paddingBottom: Math.max(24, screenHeight * 0.03),
    maxHeight: '85%',
  },
  timerModalHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: Math.max(20, screenWidth * 0.05),
    paddingVertical: Math.max(14, screenHeight * 0.018),
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(255, 255, 255, 0.1)',
  },
  timerModalTitle: {
    fontSize: Math.min(screenWidth * 0.045, 18),
    fontWeight: '600',
    color: '#ffffff',
  },
  timerModalHeaderEnded: {
    flex: 1,
    marginRight: Math.max(12, screenWidth * 0.03),
  },
  timerModalSerieLabel: {
    fontSize: Math.min(screenWidth * 0.035, 14),
    fontWeight: '500',
    color: 'rgba(255, 255, 255, 0.7)',
    marginTop: Math.max(2, screenHeight * 0.002),
  },
  timerModalHeaderRight: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: Math.max(8, screenWidth * 0.02),
  },
  timerTotalLabel: {
    fontSize: Math.min(screenWidth * 0.03, 12),
    fontWeight: '500',
    color: 'rgba(255, 255, 255, 0.5)',
  },
  timerTotalValue: {
    fontSize: Math.min(screenWidth * 0.038, 15),
    fontWeight: '600',
    color: 'rgba(255, 255, 255, 0.7)',
  },
  timerModalCloseButton: {
    padding: Math.max(4, screenWidth * 0.01),
    marginLeft: Math.max(4, screenWidth * 0.01),
    justifyContent: 'center',
    alignItems: 'center',
  },
  timerModalCloseButtonText: {
    fontSize: Math.min(screenWidth * 0.05, 20),
    color: 'rgba(255, 255, 255, 0.6)',
    fontWeight: '600',
  },
  timerModalContent: {
    paddingHorizontal: Math.max(20, screenWidth * 0.05),
    paddingTop: Math.max(12, screenHeight * 0.015),
  },
  timerRestHero: {
    alignItems: 'center',
    justifyContent: 'center',
    minHeight: Math.max(160, screenHeight * 0.22),
    paddingVertical: Math.max(24, screenHeight * 0.03),
  },
  timerRestHeroHollowWrap: {
    alignItems: 'center',
    justifyContent: 'center',
    minHeight: 240,
  },
  timerRestHeroSvg: {
    overflow: 'visible',
  },
  timerDurationRow: {
    flexDirection: 'row',
    alignItems: 'stretch',
    marginBottom: Math.max(18, screenHeight * 0.022),
  },
  timerCustomColumn: {
    flex: 1,
    minWidth: 0,
  },
  timerCustomCard: {
    flex: 1,
    backgroundColor: 'rgba(255, 255, 255, 0.05)',
    borderRadius: Math.max(12, screenWidth * 0.03),
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.12)',
    paddingVertical: Math.max(12, screenHeight * 0.015),
    paddingHorizontal: Math.max(12, screenWidth * 0.03),
  },
  timerPickerRow: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    gap: Math.max(20, screenWidth * 0.05),
  },
  timerPickerColumn: {
    alignItems: 'center',
  },
  timerPickerScroll: {
    height: 132,
    width: Math.max(64, screenWidth * 0.16),
  },
  timerPickerContent: {
    paddingVertical: 44,
  },
  timerPickerItem: {
    height: 44,
    justifyContent: 'center',
    alignItems: 'center',
  },
  timerPickerItemText: {
    fontSize: Math.min(screenWidth * 0.048, 19),
    fontWeight: '500',
    color: 'rgba(255, 255, 255, 0.35)',
  },
  timerPickerItemTextSelected: {
    color: 'rgba(255, 255, 255, 1)',
    fontWeight: '700',
    fontSize: Math.min(screenWidth * 0.055, 22),
  },
  timerPickerUnit: {
    fontSize: Math.min(screenWidth * 0.028, 12),
    fontWeight: '600',
    color: 'rgba(255, 255, 255, 0.5)',
    marginTop: Math.max(4, screenHeight * 0.005),
  },
  timerPrimaryBtn: {
    width: '100%',
    backgroundColor: 'rgba(191, 168, 77, 0.2)',
    borderRadius: Math.max(12, screenWidth * 0.04),
    paddingVertical: Math.max(16, screenHeight * 0.02),
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: 'rgba(191, 168, 77, 0.5)',
  },
  timerPrimaryBtnStop: {
    backgroundColor: '#3a3a3a',
    borderColor: 'rgba(255, 255, 255, 0.2)',
  },
  timerPrimaryBtnDisabled: {
    backgroundColor: '#3a3a3a',
    borderColor: 'rgba(255, 255, 255, 0.1)',
    opacity: 0.7,
  },
  timerPrimaryBtnText: {
    fontSize: Math.min(screenWidth * 0.045, 18),
    fontWeight: '600',
    color: 'rgba(191, 168, 77, 1)',
  },
  timerPrimaryBtnTextStop: {
    color: '#ffffff',
  },
  timerPausedButtonsRow: {
    flexDirection: 'row',
    gap: Math.max(12, screenWidth * 0.03),
    width: '100%',
  },
  timerPrimaryBtnResume: {
    flex: 1,
    backgroundColor: 'rgba(191, 168, 77, 0.25)',
    borderColor: 'rgba(191, 168, 77, 0.6)',
  },
  timerPrimaryBtnDiscard: {
    flex: 1,
    backgroundColor: '#3a3a3a',
    borderColor: 'rgba(255, 255, 255, 0.2)',
  },
  timerPrimaryBtnTextResume: {
    color: 'rgba(191, 168, 77, 1)',
  },
  timerPrimaryBtnTextDiscard: {
    color: 'rgba(255, 255, 255, 0.9)',
  },
  timerEndedObjectivesTitle: {
    fontSize: Math.min(screenWidth * 0.055, 20),
    fontWeight: '700',
    color: '#ffffff',
    marginBottom: Math.max(14, screenHeight * 0.018),
    textAlign: 'center',
  },
  timerEndedObjectivesListScroll: {
    maxHeight: Math.min(320, screenHeight * 0.4),
    marginBottom: Math.max(14, screenHeight * 0.018),
  },
  timerObjectiveGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
  },
  timerObjectiveCard: {
    width: '48%',
    minHeight: Math.max(76, screenHeight * 0.095),
    backgroundColor: 'rgba(255, 255, 255, 0.08)',
    borderRadius: Math.max(12, screenWidth * 0.03),
    padding: Math.max(14, screenWidth * 0.035),
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.12)',
    marginBottom: Math.max(10, screenHeight * 0.012),
  },
  timerObjectiveCardFullWidth: {
    width: '100%',
  },
  timerObjectiveCardLabel: {
    fontSize: Math.min(screenWidth * 0.032, 13),
    fontWeight: '500',
    color: 'rgba(255, 255, 255, 0.75)',
    marginBottom: Math.max(4, screenHeight * 0.005),
  },
  timerObjectiveCardValue: {
    fontSize: Math.min(screenWidth * 0.048, 19),
    fontWeight: '600',
    color: '#ffffff',
  },
  timerPrimaryBtnTextDisabled: {
    color: 'rgba(255, 255, 255, 0.4)',
  },
  // Video card styles (from WarmupScreen)
  videoCard: {
    backgroundColor: '#2a2a2a',
    borderRadius: Math.max(12, screenWidth * 0.04),
    padding: 0,
    marginBottom: 0,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.2)',
    shadowColor: 'rgba(255, 255, 255, 0.4)',
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 1,
    shadowRadius: 2,
    elevation: 2,
    height: Math.max(400, screenHeight * 0.525), // 400px min, 50% of screen (matches muscles card)
    overflow: 'visible',
    position: 'relative',
    width: screenWidth - Math.max(48, screenWidth * 0.12),
  },
  videoCardNoBorder: {
    borderWidth: 0,
    shadowColor: 'transparent',
    shadowOpacity: 0,
    elevation: 0,
  },
  // Match WarmupScreen: no position on container so overlays position relative to videoCard
  videoContainer: {
    flex: 1,
    width: '100%',
    height: '100%',
  },
  /* Wrapper at zIndex 0; global CSS [data-video-card] video forces <video> element to z-index -1 so overlays paint on top */
  videoWrapper: {
    flex: 1,
    width: '100%',
    height: '100%',
    zIndex: 0,
  },
  video: {
    flex: 1,
    width: '100%',
    height: '100%',
    borderRadius: Math.max(12, screenWidth * 0.04),
  },
  videoPlaceholder: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#2a2a2a',
  },
  videoPlaceholderText: {
    color: '#cccccc',
    fontSize: Math.min(screenWidth * 0.04, 16),
    textAlign: 'center',
  },
  videoDimmingLayer: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: 'rgba(0, 0, 0, 0.3)',
    zIndex: 10,
  },
  pauseOverlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: 10,
  },
  volumeIconContainer: {
    position: 'absolute',
    top: Math.max(12, screenHeight * 0.015),
    right: Math.max(12, screenWidth * 0.03),
    zIndex: 10,
  },
  volumeIconButton: {
    backgroundColor: 'rgba(0, 0, 0, 0.6)',
    borderRadius: Math.max(16, screenWidth * 0.04),
    padding: Math.max(8, screenWidth * 0.02),
    minWidth: Math.max(32, screenWidth * 0.08),
    minHeight: Math.max(32, screenWidth * 0.08),
    alignItems: 'center',
    justifyContent: 'center',
  },
  restartIconContainer: {
    position: 'absolute',
    top: Math.max(60, screenHeight * 0.075),
    right: Math.max(12, screenWidth * 0.03),
    zIndex: 10,
  },
  restartIconButton: {
    backgroundColor: 'rgba(0, 0, 0, 0.6)',
    borderRadius: Math.max(16, screenWidth * 0.04),
    padding: Math.max(8, screenWidth * 0.02),
    minWidth: Math.max(32, screenWidth * 0.08),
    minHeight: Math.max(32, screenWidth * 0.08),
    alignItems: 'center',
    justifyContent: 'center',
  },
  // End Workout Button Styles
  endWorkoutButton: {
    backgroundColor: 'rgba(255, 68, 68, 0.2)',
    height: Math.max(50, screenHeight * 0.06), // Match purchase button height
    width: Math.max(280, screenWidth * 0.7), // Match purchase button width
    borderRadius: Math.max(12, screenWidth * 0.04),
    marginTop: Math.max(24, screenHeight * 0.03),
    marginBottom: Math.max(20, screenHeight * 0.025),
    alignItems: 'center',
    justifyContent: 'center',
    alignSelf: 'center',
    // Shadow removed - was causing offset bottom shadow
    shadowOpacity: 0,
    elevation: 0,
  },
  endWorkoutButtonActive: {
    backgroundColor: 'rgba(191, 168, 77, 0.2)',
    opacity: 1,
    // Shadow removed - was causing offset bottom shadow
    shadowOpacity: 0,
    elevation: 0,
  },
  endWorkoutButtonDisabled: {
    backgroundColor: 'rgba(255, 255, 255, 0.2)',
    borderColor: 'rgba(255, 255, 255, 0.2)',
    borderWidth: 1,
  },
  endWorkoutButtonText: {
    color: 'rgba(255, 68, 68, 0.8)',
    fontSize: Math.min(screenWidth * 0.045, 18),
    fontWeight: '600',
  },
  endWorkoutButtonTextActive: {
    color: 'rgba(191, 168, 77, 1)',
    fontSize: Math.min(screenWidth * 0.045, 18),
    fontWeight: '700',
  },
  endWorkoutButtonTextDisabled: {
    color: 'rgba(255, 255, 255, 0.5)',
    fontSize: Math.min(screenWidth * 0.045, 18),
    fontWeight: '600',
  },
  endWorkoutButtonTextLoading: {
    color: 'rgba(191, 168, 77, 0.8)',
    fontSize: Math.min(screenWidth * 0.045, 18),
    fontWeight: '600',
  },
  // Button container for horizontal layout
  buttonContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: Math.max(10, screenWidth * 0.025),
  },
  // Main save button
  inputSetButton: {
    flex: 1,
    backgroundColor: 'rgba(191, 168, 77, 0.2)',
    borderRadius: Math.max(12, screenWidth * 0.04),
    paddingVertical: Math.max(16, screenHeight * 0.02),
    paddingHorizontal: Math.max(20, screenWidth * 0.05),
    alignItems: 'center',
    justifyContent: 'center',
    // Shadow removed - was causing offset bottom shadow
    shadowOpacity: 0,
    elevation: 0,
  },
  inputSetButtonText: {
    color: 'rgba(191, 168, 77, 1)',
    fontSize: Math.min(screenWidth * 0.04, 16),
    fontWeight: '600',
    textAlign: 'center',
  },
  inputSetButtonDisabled: {
    backgroundColor: '#666666',
    opacity: 0.6,
    shadowOpacity: 0,
  },
  inputSetButtonTextDisabled: {
    color: '#cccccc',
  },
  // Small list screen button
  listScreenButton: {
    width: Math.max(60, screenWidth * 0.15),
    backgroundColor: 'rgba(191, 168, 77, 0.2)',
    borderRadius: Math.max(12, screenWidth * 0.04),
    paddingVertical: Math.max(14, screenHeight * 0.017),
    alignItems: 'center',
    justifyContent: 'center',
    // Shadow removed - was causing offset bottom shadow
    shadowOpacity: 0,
    elevation: 0,
  },
  // Exercise controls row
  exerciseControlsRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: Math.max(12, screenHeight * 0.015),
    marginHorizontal: Math.max(16, screenWidth * 0.04),
  },
  // Swap exercise button
  swapExerciseButton: {
    backgroundColor: '#3a3a3a',
    borderRadius: Math.max(8, screenWidth * 0.02),
    paddingHorizontal: Math.max(16, screenWidth * 0.04),
    paddingVertical: Math.max(8, screenHeight * 0.01),
    flexDirection: 'row',
    alignItems: 'center',
    gap: Math.max(8, screenWidth * 0.02),
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.2)',
    shadowColor: 'rgba(255, 255, 255, 0.4)',
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 1,
    shadowRadius: 2,
    elevation: 2,
  },
  swapExerciseButtonText: {
    color: '#ffffff',
    fontSize: Math.min(screenWidth * 0.035, 14),
    fontWeight: '600',
  },
  // Set control buttons
  setControlButtons: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: Math.max(8, screenWidth * 0.02),
  },
  setControlButton: {
    backgroundColor: '#3a3a3a',
    borderRadius: Math.max(8, screenWidth * 0.02),
    padding: Math.max(8, screenWidth * 0.02),
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.2)',
    shadowColor: 'rgba(255, 255, 255, 0.4)',
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 1,
    shadowRadius: 2,
    elevation: 2,
    justifyContent: 'center',
    alignItems: 'center',
    minWidth: Math.max(32, screenWidth * 0.08),
    minHeight: Math.max(32, screenWidth * 0.08),
  },
  setControlButtonDisabled: {
    backgroundColor: '#2a2a2a',
    borderColor: 'rgba(255, 255, 255, 0.1)',
    shadowOpacity: 0,
    elevation: 0,
  },
  // Swap modal styles
  swapModalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    justifyContent: 'flex-end',
  },
  swapModalBackdrop: {
    flex: 1,
  },
  swapModalContainer: {
    backgroundColor: '#2a2a2a',
    borderTopLeftRadius: Math.max(20, screenWidth * 0.05),
    borderTopRightRadius: Math.max(20, screenWidth * 0.05),
    height: '90%',
    maxHeight: Math.max(800, screenHeight * 0.8),
  },
  swapModalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: Math.max(20, screenWidth * 0.05),
    paddingVertical: Math.max(20, screenHeight * 0.025),
  },
  swapModalTitle: {
    color: '#ffffff',
    fontSize: Math.min(screenWidth * 0.06, 24),
    fontWeight: '600',
    paddingLeft: Math.max(20, screenWidth * 0.05),
  },
  swapModalCloseButton: {
    width: Math.max(30, screenWidth * 0.075),
    height: Math.max(30, screenWidth * 0.075),
    borderRadius: Math.max(15, screenWidth * 0.037),
    backgroundColor: '#44454B',
    alignItems: 'center',
    justifyContent: 'center',
  },
  swapModalCloseButtonText: {
    color: '#ffffff',
    fontSize: Math.min(screenWidth * 0.04, 16),
    fontWeight: '600',
  },
  swapModalContent: {
    flex: 1,
    paddingHorizontal: Math.max(20, screenWidth * 0.05),
    paddingTop: Math.max(20, screenHeight * 0.025),
  },
  swapModalSubtitle: {
    fontSize: Math.min(screenWidth * 0.04, 16),
    marginBottom: Math.max(18, screenHeight * 0.022),
    opacity: 1,
    paddingLeft: Math.max(20, screenWidth * 0.05),
  },
  sugerenciasText: {
    color: '#ffffff',
    fontSize: Math.min(screenWidth * 0.04, 16),
    fontWeight: '400',
  },
  creatorNameText: {
    color: '#ffffff',
    fontSize: Math.min(screenWidth * 0.04, 16),
    fontWeight: '600',
  },
  currentExerciseSection: {
    marginBottom: Math.max(24, screenHeight * 0.03),
  },
  currentExerciseLabel: {
    color: '#ffffff',
    fontSize: Math.min(screenWidth * 0.04, 16),
    fontWeight: '600',
    marginBottom: Math.max(12, screenHeight * 0.015),
    opacity: 1,
    paddingLeft: Math.max(20, screenWidth * 0.05),
  },
  // Card styles
  expandedExerciseCard: {
    backgroundColor: '#3a3a3a',
    borderRadius: Math.max(12, screenWidth * 0.04),
    padding: Math.max(12, screenWidth * 0.03),
    flexDirection: 'column',
    marginBottom: Math.max(12, screenHeight * 0.015),
    position: 'relative',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.2)',
    shadowColor: 'rgba(255, 255, 255, 0.4)',
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 1,
    shadowRadius: 2,
    elevation: 2,
  },
  compactExerciseCard: {
    backgroundColor: '#3a3a3a',
    borderRadius: Math.max(12, screenWidth * 0.04),
    paddingVertical: Math.max(16, screenHeight * 0.02),
    paddingHorizontal: Math.max(16, screenWidth * 0.04),
    marginBottom: Math.max(12, screenHeight * 0.015),
    flexDirection: 'column',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.2)',
    shadowColor: 'rgba(255, 255, 255, 0.4)',
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 1,
    shadowRadius: 2,
    elevation: 2,
  },
  expandedCardBorder: {
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.2)',
  },
  compactCardBorder: {
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.2)',
  },
  exerciseNameContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    width: '100%',
  },
  swapIconButton: {
    backgroundColor: '#44454B',
    borderRadius: Math.max(20, screenWidth * 0.05),
    width: Math.max(40, screenWidth * 0.1),
    height: Math.max(40, screenWidth * 0.1),
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.2)',
    shadowColor: 'rgba(255, 255, 255, 0.4)',
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 1,
    shadowRadius: 2,
    elevation: 2,
  },
  currentExerciseVideoContainer: {
    width: '85%',
    height: 430, // Original height
    borderRadius: Math.max(12, screenWidth * 0.04),
    marginBottom: Math.max(12, screenHeight * 0.015),
    overflow: 'hidden',
    alignSelf: 'center',
  },
  currentExerciseVideo: {
    width: '100%',
    height: '100%',
  },
  currentExerciseVideoPlaceholder: {
    width: '100%',
    height: '100%',
    backgroundColor: '#666666',
    justifyContent: 'center',
    alignItems: 'center',
  },
  currentExerciseVideoPlaceholderText: {
    color: '#ffffff',
    fontSize: Math.min(screenWidth * 0.025, 10),
    fontWeight: '500',
    textAlign: 'center',
  },
  swapModalVideoContainer: {
    width: '100%',
    height: '100%',
    position: 'relative',
  },
  swapModalVideo: {
    width: '100%',
    height: '100%',
  },
  swapModalDimmingLayer: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: 'rgba(0, 0, 0, 0.3)',
    zIndex: 1,
  },
  swapModalPauseOverlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: 2,
  },
  swapModalVolumeOverlay: {
    position: 'absolute',
    top: Math.max(12, screenHeight * 0.015),
    right: Math.max(12, screenWidth * 0.03),
    width: Math.max(40, screenWidth * 0.1),
    height: Math.max(40, screenWidth * 0.1),
    borderRadius: Math.max(20, screenWidth * 0.05),
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: 3,
  },
  currentExerciseContent: {
    width: '100%',
  },
  currentExerciseName: {
    color: '#ffffff',
    fontSize: Math.min(screenWidth * 0.04, 16),
    fontWeight: '600',
  },
  alternativeExerciseContent: {
    flex: 1,
  },
  alternativeExerciseName: {
    color: '#ffffff',
    fontSize: Math.min(screenWidth * 0.04, 16),
    fontWeight: '600',
  },
  loadingContainer: {
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: Math.max(40, screenHeight * 0.05),
  },
  loadingText: {
    color: '#ffffff',
    fontSize: Math.min(screenWidth * 0.04, 16),
    marginTop: Math.max(12, screenHeight * 0.015),
    opacity: 0.8,
  },
  noAlternativesContainer: {
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: Math.max(40, screenHeight * 0.05),
  },
  noAlternativesText: {
    color: '#ffffff',
    fontSize: Math.min(screenWidth * 0.04, 16),
    opacity: 0.6,
    textAlign: 'center',
  },
  // Info icon container (top-right of objective cards)
  infoIconContainer: {
    position: 'absolute',
    top: Math.max(8, screenHeight * 0.01),
    right: Math.max(8, screenWidth * 0.02),
    zIndex: 10,
  },
  // Objective Info Modal Styles
  objectiveInfoModalOverlay: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  objectiveInfoModalBackdrop: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: 'rgba(0, 0, 0, 0.7)',
  },
  objectiveInfoModalContent: {
    backgroundColor: '#2a2a2a',
    borderRadius: Math.max(12, screenWidth * 0.04),
    width: Math.max(350, screenWidth * 0.9),
    maxWidth: 400,
    height: Math.max(500, screenHeight * 0.7),
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.2)',
    shadowColor: 'rgba(255, 255, 255, 0.4)',
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 1,
    shadowRadius: 2,
    elevation: 2,
    overflow: 'visible',
  },
  
  objectiveInfoScrollContainer: {
    flex: 1,
    position: 'relative',
  },
  
  objectiveInfoScrollView: {
    flex: 1,
    paddingHorizontal: Math.max(24, screenWidth * 0.06),
  },
  objectiveInfoModalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: Math.max(16, screenHeight * 0.02),
  },
  objectiveInfoModalTitle: {
    color: '#ffffff',
    fontSize: Math.min(screenWidth * 0.055, 22),
    fontWeight: '600',
    flex: 1,
    textAlign: 'left',
    paddingLeft: Math.max(25, screenWidth * 0.06),
    paddingTop: Math.max(25, screenHeight * 0.03),
  },
  objectiveInfoCloseButton: {
    width: Math.max(30, screenWidth * 0.075),
    height: Math.max(30, screenWidth * 0.075),
    borderRadius: Math.max(15, screenWidth * 0.037),
    backgroundColor: '#44454B',
    alignItems: 'center',
    justifyContent: 'center',
    marginLeft: Math.max(12, screenWidth * 0.03),
    marginRight: Math.max(10, screenWidth * 0.03),
    marginTop: Math.max(5, screenHeight * 0.01),
  },
  objectiveInfoCloseButtonText: {
    color: '#ffffff',
    fontSize: Math.min(screenWidth * 0.04, 16),
    fontWeight: '600',
  },
  objectiveInfoModalDescription: {
    color: '#ffffff',
    fontSize: Math.min(screenWidth * 0.04, 16),
    fontWeight: '400',
    lineHeight: Math.max(24, screenHeight * 0.03),
    opacity: 0.9,
    marginBottom: Math.max(20, screenHeight * 0.025),
  },
  disclaimersSection: {
    marginTop: Math.max(20, screenHeight * 0.025),
    paddingTop: Math.max(16, screenHeight * 0.02),
    paddingBottom: 24,
    borderTopWidth: 1,
    borderTopColor: 'rgba(255, 255, 255, 0.1)',
  },
  disclaimersTitle: {
    color: 'rgba(191, 168, 77, 1)',
    fontSize: Math.min(screenWidth * 0.045, 18),
    fontWeight: '600',
    marginBottom: Math.max(12, screenHeight * 0.015),
  },
  disclaimerText: {
    color: '#ffffff',
    fontSize: Math.min(screenWidth * 0.035, 14),
    fontWeight: '400',
    lineHeight: Math.max(20, screenHeight * 0.025),
    opacity: 0.8,
    marginBottom: Math.max(8, screenHeight * 0.01),
  },
  scrollIndicator: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    height: 35,
    backgroundColor: 'rgba(42, 42, 42, 0.9)',
    borderBottomLeftRadius: Math.max(16, screenWidth * 0.04),
    alignItems: 'center',
    justifyContent: 'center',
    paddingTop: 8,
    paddingBottom: 8,
  },
  scrollIndicatorText: {
    fontSize: 11,
    fontWeight: '500',
    color: '#ffffff',
    textAlign: 'center',
  },
});

// Add loading overlay styles
// Confirmation Modal Styles - Simplified and improved UI
const confirmModalStyles = (screenWidth, screenHeight) => StyleSheet.create({
  confirmModalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.8)',
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: Math.max(24, screenWidth * 0.06),
  },
  confirmModalBackdrop: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
  },
  confirmModalContent: {
    backgroundColor: '#2a2a2a',
    borderRadius: Math.max(20, screenWidth * 0.05),
    padding: Math.max(32, screenWidth * 0.08),
    width: '100%',
    maxWidth: Math.min(screenWidth * 0.85, 360),
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.15)',
    shadowColor: 'rgba(255, 255, 255, 0.3)',
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 1,
    shadowRadius: 4,
    elevation: 8,
    alignItems: 'center',
  },
  confirmModalTitle: {
    color: '#ffffff',
    fontSize: Math.min(screenWidth * 0.065, 26),
    fontWeight: '700',
    marginBottom: Math.max(20, screenHeight * 0.025),
    textAlign: 'center',
    letterSpacing: 0.5,
  },
  confirmModalMessage: {
    color: 'rgba(255, 255, 255, 0.75)',
    fontSize: Math.min(screenWidth * 0.045, 18),
    fontWeight: '500',
    marginBottom: Math.max(32, screenHeight * 0.04),
    textAlign: 'center',
    lineHeight: Math.max(24, screenHeight * 0.03),
  },
  confirmModalButtons: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: Math.max(16, screenWidth * 0.04),
    width: '100%',
  },
  confirmModalButton: {
    flex: 1,
    paddingVertical: Math.max(12, screenHeight * 0.015),
    paddingHorizontal: Math.max(16, screenWidth * 0.04),
    borderRadius: Math.max(12, screenWidth * 0.03),
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1.5,
    minHeight: Math.max(44, screenHeight * 0.055),
  },
  confirmModalButtonCancel: {
    backgroundColor: 'rgba(255, 255, 255, 0.08)',
    borderColor: 'rgba(255, 255, 255, 0.25)',
  },
  confirmModalButtonConfirm: {
    backgroundColor: 'rgba(191, 168, 77, 0.25)',
    borderColor: 'rgba(191, 168, 77, 0.7)',
  },
  confirmModalButtonDestructive: {
    backgroundColor: 'rgba(255, 59, 48, 0.15)',
    borderColor: 'rgba(255, 59, 48, 0.6)',
  },
  confirmModalButtonText: {
    color: 'rgba(191, 168, 77, 1)',
    fontSize: Math.min(screenWidth * 0.045, 18),
    fontWeight: '600',
  },
  confirmModalButtonTextCancel: {
    color: 'rgba(255, 255, 255, 0.9)',
    fontSize: Math.min(screenWidth * 0.045, 18),
    fontWeight: '600',
  },
  confirmModalButtonTextDestructive: {
    color: 'rgba(255, 59, 48, 1)',
    fontSize: Math.min(screenWidth * 0.045, 18),
    fontWeight: '600',
  },
});

const createLoadingOverlayStyles = (screenWidth, screenHeight) => StyleSheet.create({
  overlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.85)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  loadingContent: {
    backgroundColor: '#2a2a2a',
    borderRadius: Math.max(15, screenWidth * 0.04),
    padding: Math.max(30, screenWidth * 0.08),
    alignItems: 'center',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.2)',
    shadowColor: 'rgba(255, 255, 255, 0.4)',
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 1,
    shadowRadius: 2,
    elevation: 2,
    overflow: 'visible',
  },
  loadingText: {
    color: '#ffffff',
    fontSize: Math.min(screenWidth * 0.045, 18),
    fontWeight: '600',
    marginTop: 15,
  },
  loadingSubtext: {
    color: 'rgba(255, 255, 255, 0.7)',
    fontSize: Math.min(screenWidth * 0.035, 14),
    fontWeight: '400',
    marginTop: 8,
    textAlign: 'center',
  },
  
  // Intensity Cards - Exact copy of swap modal compactExerciseCard
  intensityVideoSection: {
    marginTop: 24,
    paddingTop: 20,
    borderTopWidth: 1,
    borderTopColor: 'rgba(255, 255, 255, 0.15)',
  },
  
  intensityVideoTitle: {
    color: '#ffffff',
    fontSize: 18,
    fontWeight: '600',
    marginBottom: 16,
    textAlign: 'center',
  },
  
  
  intensityCard: {
    backgroundColor: '#3a3a3a',
    borderRadius: Math.max(12, screenWidth * 0.04),
    paddingVertical: Math.max(16, screenHeight * 0.02),
    paddingHorizontal: Math.max(16, screenWidth * 0.04),
    marginBottom: Math.max(12, screenHeight * 0.015),
    flexDirection: 'column',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.2)',
    shadowColor: 'rgba(255, 255, 255, 0.4)',
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 1,
    shadowRadius: 2,
    elevation: 2,
  },
  
  intensityCardExpanded: {
    // Expanded state - same as normal card
  },
  
  intensityCardLabel: {
    color: '#ffffff',
    fontSize: Math.min(screenWidth * 0.05, 20),
    fontWeight: '600',
    textAlign: 'center',
    marginBottom: 8,
  },
  
  intensityCardVideoContainer: {
    width: '85%',
    height: 250,
    borderRadius: Math.max(12, screenWidth * 0.04),
    overflow: 'hidden',
    alignSelf: 'center',
    marginTop: 8,
  },
  
  intensityCardVideo: {
    width: '100%',
    height: '100%',
    opacity: 0.7,
  },
  
  intensityVideoOverlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'rgba(0, 0, 0, 0.3)',
  },

  muscleSilhouetteWrapper: {
    width: '100%',
    marginBottom: 0,
    paddingBottom: 0,
    // GPU acceleration hints for better paint performance
    transform: [{ translateZ: 0 }], // Promote to GPU layer
  },
  // Muscle activation card styles
  muscleSilhouetteContainerCard: {
    width: '100%',
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 0,
    paddingBottom: 0,
    // GPU acceleration hints for better paint performance
    transform: [{ translateZ: 0 }], // Promote to GPU layer
    height: Math.max(300, screenHeight * 0.36), // Slightly shorter silhouette area
    flexShrink: 0,
  },
  muscleEmptyState: {
    width: '100%',
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: Math.max(16, screenWidth * 0.04),
    minHeight: 240,
  },
  muscleEmptyText: {
    color: '#cccccc',
    fontSize: Math.min(screenWidth * 0.035, 14),
    textAlign: 'center',
  },
  muscleToImplementsSpacer: {
    width: '100%',
    height: Math.max(80, screenHeight * 0.1),
    flexShrink: 0,
    flexGrow: 0,
    backgroundColor: 'rgba(255, 0, 0, 0.2)', // Temporary - to verify it's rendering
  },
  // Implements section under silhouette
  implementsSection: {
    marginTop: 0,
    paddingTop: 0,
    width: '100%',
    marginBottom: 0,
    paddingBottom: 0,
    flexShrink: 0,
  },
  implementsSubtitle: {
    marginTop: 0,
    marginBottom: 12,
    paddingLeft: 0,
  },
  implementsRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'flex-start',
    paddingRight: 8,
  },
  implementsPillContainer: {
    marginBottom: 0,
  },
  implementsPill: {
    // Override some spacing to reuse editButton visual style
    alignSelf: 'flex-start',
  },
  implementsPillText: {
    // Slight tweak if needed later (currently just inherit editButtonText)
  },
  muscleEmptyStateInline: {
    paddingHorizontal: Math.max(10, screenWidth * 0.025),
    paddingVertical: Math.max(6, screenHeight * 0.007),
  },
  muscleEmptyTextInline: {
    color: '#cccccc',
    fontSize: Math.min(screenWidth * 0.035, 14),
  },
});

export { createStyles, confirmModalStyles, createLoadingOverlayStyles };
