sonar.projectKey=wake
sonar.projectName=Wake
sonar.host.url=http://localhost:9000
sonar.sources=apps/pwa/src,apps/creator-dashboard/src,apps/landing/src,functions/src
sonar.exclusions=**/node_modules/**,**/dist/**,**/build/**,functions/lib/**,**/__tests__/**,**/*.test.*
sonar.tests=functions/tests
sonar.test.inclusions=**/*.test.*
sonar.javascript.environments=browser,node
sonar.qualitygate.wait=true
